# Generated by Django 2.2.6 on 2019-10-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191025_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='liveProject_url',
        ),
    ]
