# Generated by Django 2.2.6 on 2019-12-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20191106_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
